# Generated by Django 4.0.3 on 2022-03-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='object_model',
            new_name='model_name',
        ),
    ]
