# Generated by Django 4.0.3 on 2022-03-06 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_approvalchange_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='approval',
            name='initiated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
