# Generated by Django 4.0.3 on 2022-03-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_approval_description_approval_initiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
