# Generated by Django 4.0.3 on 2022-03-06 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approval', '0005_approval_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='pending_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
