# Generated by Django 4.0.3 on 2022-03-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_approval_pending_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalchange',
            name='final_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='approvalchange',
            name='initial_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
